### ISSUE TITLE
Broken links on the website

### ISSUE THREAD

**Issue by moskinson** [GraphWalker/graphwalker.org#10]
Go to http://graphwalker.org/contact
Click on
   https://github.com/GraphWalker/graphwalker-core/issues
   https://github.com/GraphWalker/graphwalker-cli/issues

What happened:
Page not found. 404 response

Extra notes:
To visualize other links like "GraphWalker open Issues" you need to be logged in Github. Maybe it is a good idea to add a comment to mention it

**Comment by nilols** [comment]
Thanks for reporting the issue.
We changed the project layout a while back, it was too much overhead having a repository for each subproject, instead we now use modules.

**Comment by nilols** [comment]
Is this still an issue?
