### ISSUE TITLE
Using multiple models in a pre-defined test 

### ISSUE THREAD

**Issue by ChristofferJohansson** [GraphWalker/graphwalker.org#2]
Hi! I've been using an older version of graphwalker for some time now, I've held off on updating because of the the new functionality planned for 3.2 with C# support and the JSON functionality.
So now with the new release I've started refactoring our entire GUI test automation framework =)

My question was regarding separating the specific tests and the models (the way you had to do it before when using Modelhandlers). Under the modeling syntax page on the new website there is a section on how to be able to use multiple models from the CLI, is there any way to do something similar but from a separate file?

**Comment by KristianKarl** [comment]
Hi!
Coolness! Give us any feedback here, and we'll try to support you. The new WebSocket/JSON features are quite new.

What do you mean with:
*is there any way to do something similar but from a separate file?*

**Comment by ChristofferJohansson** [comment]
I was thinking of defining tests using multiple models from somewhere separate from where I defined the steps in the model, but now after taking a step back I think I've found a way to do it. Noticed there was a different example under "How to use graphwalker" that showed how you defined the modelpath and context in a testbuilder. But thanks for the quick response!

**Comment by KristianKarl** [comment]
Ok, I just added C# websocket exmple: https://github.com/GraphWalker/graphwalker-example/tree/master/c-sharp-websocket/SmallModel
You might wanna have a look at that.
