### ISSUE TITLE
Combining different stop conditions

### ISSUE THREAD

**Issue by SKAhster** [GraphWalker/graphwalker.org#3]
I would like to see the "Combining different stop conditions" page on your website completed, as it may help me with my newbie (to Java/Selenium) question of how to perform a RandomPath:EdgeCoverage(100) followed by AStar:ReachedVertex("vertex_name"). The code I tried looks like this:

    @Test
    public void runFunctionalTest() {
        new TestBuilder()

                .setModel(MODEL_PATH)
                .setContext(new ServiceNowTest())
                .setStart("aLaunchApplication")
                .setPathGenerator(new RandomPath(new EdgeCoverage(100)))
                .setPathGenerator(new AStarPath(new ReachedVertex("vAppClosed")))
                .execute();
    }

**Comment by KristianKarl** [comment]
Thanks for the input. Your code needs to look like:
~~~java
@Test
public void runFunctionalTest() {
  CombinedPath combinedPath = new CombinedPath();
  combinedPath.addPathGenerator(new RandomPath(new EdgeCoverage(100)));
  combinedPath.addPathGenerator(new AStarPath(new ReachedVertex("vAppClosed")));
  new TestBuilder()
    .setModel(MODEL_PATH)
    .setContext(new ServiceNowTest())
    .setStart("aLaunchApplication")
    .setPathGenerator(combinedPath)
    .execute();
}
~~~
