### ISSUE TITLE
Spelling comments on graphwalker.org website

### ISSUE THREAD

**Issue by f97gujo** [GraphWalker/graphwalker.org#4]
Great product, and nice website, but I think I can contribute with some minor suggestions of proof reading.

Best regards
Gunnar

http://graphwalker.org/index

Under What is GraphWalker?
For the tester:
First sentence: IS: It's easy to design for test automation, even if you don't have any or little programming skills. 
The second half of the sentence could be read to mean "even if you don't have little programming skills", but what is meant (I think) is "even if you have no, or little, programming skills.

For the test automation developer:
Second sentence: IS:  It's is highly modularized, and it's easy to extend if you need to customize it.
Should be:  It is highly modularized, and it's easy to extend if you need to customize it. OR  It's highly modularized, and it's easy to extend if you need to customize it.

For the team:
Second sentence: IS:  Getting feed-back from team members and stakeholders is so much more easier with models.
Should be:  Getting feed-back from team members and stakeholders is so much easier with models.

For whoever pays the bills:
First sentence: IS: The models creates an abstraction layer between the test design and the implementing automation code.
Should be: The models create an abstraction layer between the test design and the implementing automation code.

Third sentence: IS: Remember that the test automation (code and design) will have as long life time expectancy as the system under test.
Could be: Remember that the test automation (code and design) will have as long a life time expectancy as the system under test.

Maven
Third sentence: IS: Add this to your pom.file
Could be: Add this to your pom.xml file

License, and also foot of page (all pages seen):
IS: GraphWalker is a MIT lincensed Open Soure project.
Should be: GraphWalker is a MIT licensed Open Source project.

http://graphwalker.org/docs
Missing anything?
First sentence: IS: If there's documentation you miss.
Should be: If there's documentation you miss, if existing docs are wrong, or the english is bad or has typos, please let us know!

http://graphwalker.org/docs/gw_model_syntax

Under The model is a directed graph
Second paragraph, final sentence, feel the "it" is redundant. Try reading it while skipping text between commas
Designing a test, using a directed graph, it might look like this:

Edge:
Second sentence: IS: It is whatever action is need to be made in order to reach the next state. 
Should be: It is whatever action is needed to be made in order to reach the next state.

First bulletpoint: IS: GraphWalker only accepts on-way directed edges (arrows).
Should be: GraphWalker only accepts one-way directed edges (arrows).

Start vertex
Fourth bulletpoint: IS: The Start vertex will no be included in any generated path
Should be: The Start vertex will not be included in any generated path

Label:
Second box: IS: Some_othe_name
Could be: Some_other_name

Guards- Only for an edge
First sentence: IS: Guards are a mechanism only associated to edges.
Could be: Guards are a mechanism only associated with edges.

Second sentence: IS: Their role are the same as an if-statement, and makes an edge eligible or not for being walked.
Should be: Their roles are the same as an if-statement, and makes an edge eligible or not for being walked.

Action - Only for an edge
First sentence: IS: Actions are a mechanisms only associated to edges.
Should be: Actions are mechanisms only associated to edges. OR Action is a mechanism only associated to edges.

Multiple models
Fifth sentence: IS: Lets say you have a system that you want to test, and you would need to log in to do that. 
Should be; Let's say you have a system that you want to test, and you would need to log in to do that. 

Third paragraph
First sentence: IS: When flatting models, several models are merged into on single model, which then is being traversed by GraphWalker.
Could be: When flattening models, several models are merged into on single model, which then is being traversed by GraphWalker. 

Third sentence: IS: GraphWalker is executing every model in it's own context.
Could be: GraphWalker is executing every model in its own context.

**Comment by KristianKarl** [comment]
Great feedback! Thanks. I believe I updated all your sugegstions.
The text in the image will be fixed later.

I think you could have made your changes as a pull request, and perhaps saved yourself some time. I should update he docs, for the future.

**Comment by f97gujo** [comment]
I am sorry, but to new and to unsure in the Git environment to dare try it. And did not know if the webpage was part of the git-project.

Will see what I can do next time.

BR
Gunnar
________________________________

**Comment by KristianKarl** [comment]
np!

I added a bit of information on http://graphwalker.org/docs

But I guess I should add a how-to as well :-)
I'll do that as soon as possible.

**Comment by haider22** [comment]
kristian i fellow all rule to run graphwalker i install java and then maven and the path both of them but when i click  graphwalker.jar exe file it not run plz help what i need to do...thanks
