### ISSUE TITLE
Example integration of a new algorithm

### ISSUE THREAD

**Issue by bilred** [GraphWalker/graphwalker.org#5]
Hi, is it possible to have an example or tutorial for adding a new algorithm, step by step. with the methods and java objects that are used mandatory ?
thank you,

**Comment by KristianKarl** [comment]
Good suggestion! I'm gonna write a how to, that describes how to write a new algo.

**Comment by bilred** [comment]
ok, send me the link as soon possible, I need to understand more. thank you

**Comment by bilred** [comment]
what is the news

**Comment by nilols** [comment]
Hi Billel, I added a example in [graphwalker-example](https://github.com/GraphWalker/graphwalker-example), check under the algorithm folder. I made it with java 8 (stream and lambda) so the travis builds fails (will fix it tomorrow), but if you have java 8 you should just need to run "mvn graphwalker:test" in the algorithm folder, the test contains a model, with one vertex and multiple loop edges. The algorithm will sort them in a descending order. The path generator will use the algorithm when finding the next step to take. Let me know if you find anything unclear.
