### ISSUE TITLE
Instruction fix - The Pet Clinic example

### ISSUE THREAD

**Issue by Matt--** [GraphWalker/graphwalker.org#7]
Just working through the tutorial. This folder does not (or no longer) exist in the the spring-petclinic project. 

    *The Models - The Test Design*
    The models can be found in folder:

    src/main/resources/com/company/

**Comment by KristianKarl** [comment]
The folder is correct:
https://github.com/GraphWalker/graphwalker-example/tree/master/java-petclinic/src/main/resources/com/company
